all:
  vars:
    ansible_ssh_private_key_file: /Users/admin/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
  children:
    pizero:
      hosts:
        dietpi-zero:
          ansible_host: 192.168.178.149
          ansible_user: root
          ansible_port: 2222
    raspberry:
      hosts:
        raspi5:
          ansible_host: 192.168.178.144
          ansible_user: pi
          ansible_port: 2222
    proxmox:
      hosts:
        nuc10:
          ansible_host: 192.168.178.147
          ansible_user: root
          ansible_port: 2222
    proxmox_vms:
      hosts:
        teamspeak:
          ansible_host: 192.168.178.150
          ansible_user: teamspeak
          ansible_port: 2222