# install docker
- name: Install ca-certificate and curl
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl

- name: Create folder for keyring
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "0755"

- name: Add docker repository
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/debian
      Suites: bookworm
      Components: stable
      Architectures: arm64
      Signed-By: /etc/apt/keyrings/docker.asc
    dest: /etc/apt/sources.list.d/docker.sources

- name: Apt update after adding docker repo
  ansible.builtin.apt:
    update_cache: true

- name: Install docker packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Enable and start docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Add pi user to docker group
  ansible.builtin.user:
    name: pi
    groups: docker
    append: yes

- name: Verify docker with hello-world
  ansible.builtin.command:
    cmd: docker run hello-world
  register: hello_world_output
  changed_when: false
  become_user: pi

- name: Show hello-world output
  ansible.builtin.debug:
    var: hello_world_output.stdout
