services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_mysql_root_password }}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ nextcloud_mysql_password }}"
    volumes:
      - ./db:/var/lib/mysql

  app:
    image: nextcloud:latest
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - db
    volumes:
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./apps:/var/www/html/custom_apps
