#### order ####
# apt update + upgrade
# Pakete installieren – nginx, fail2ban, ufw, wireguard
# SSH absichern – Port 2222, Passwort-Login deaktivieren, Key hinterlegen
# UFW konfigurieren – Ports freigeben
# Fail2Ban konfigurieren
# Unnötige Dienste deaktivieren – bluetooth, ModemManager, node_exporter
# WireGuard konfigurieren
# Docker installieren

- name: setup pi5
  hosts: raspberry
  become: true 
  tasks:

# making sure the system is up to date
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: apt upgrade
      ansible.builtin.apt:
        upgrade: safe

# installing some packages
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - fail2ban
        - nginx
        - ufw
        - wireguard

# copy local ssh pub key onto server
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

# disable password auth and activate ssh
    - name: disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

# change ssh port
    - name: change ssh port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 2222'

# restart the systemd service and make sure it's running
    - name: Restarting sshd
      ansible.builtin.systemd_service:
        state: restarted
        name: sshd
        
# setup fail2ban
    - name: Copy config file
      ansible.builtin.copy:
        src: files/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'

# restart fail2ban
    - name: restart fail2ban service
      ansible.builtin.systemd_service:
        state: restarted
        name: fail2ban

# deactivate not needed services 
    - name: stop bluetooth
      ansible.builtin.systemd_service:
        state: stopped
        name: bluetooth
        enabled: false
        
    - name: stop modemmanager
      ansible.builtin.systemd_service:
        state: stopped
        name: ModemManager
        enabled: false

    - name: disable node_exporter if present
      ansible.builtin.systemd_service:
        name: node_exporter
        state: stopped
        enabled: false
      ignore_errors: true

# configure wireguard
    - name: copy wireguard config
      ansible.builtin.copy:
        content: "{{ wireguard_config }}"
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: '0600'

# start wireguard
    - name: enable and start wireguard service
      ansible.builtin.systemd_service:
        enabled: true
        state: started
        name: wg-quick@wg0

# configure ufw
    - name: configure ufw
      ansible.builtin.include_tasks: ../tasks/ufw.yml

# install docker
    - name: install docker
      ansible.builtin.include_tasks: ../tasks/docker-install-arm64.yml